[package]
name = "rusty-cde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
ndarray = {version = "0.15.6", features = ["approx"]}
ndarray-linalg = {version="0.16.0", features = ["intel-mkl-static"]}
ndarray-npy = "0.8.1"
egui = "0.21.0"
egui_extras = "0.21.0"
bevy_egui = "0.20.3"
config = "0.13.3"
rand = "0.8.5"
rand_distr = "0.4.3"
plotters = "0.3.4"
bevy_panorbit_camera = "0.5.0"
num-traits = "0.2.15"
approx = "0.5.1"
chrono = "0.4.24"
serde = "1.0.163"
toml = "0.7.3"
itertools = "0.10.5"
physical_constants = "0.5.0"
samplerate = "0.2.4"