[package]
name = "cardiotrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
bevy = "0.13.0"
bevy_egui = {version = "0.26.0", default-features = false, features = ["open_url", "default_fonts", "render"]}
bevy_panorbit_camera = "0.17.0"
bevy_embedded_assets = "0.10.2"
bincode = "1.3.3"
chrono = "0.4.24"
egui = "0.26.2"
egui_extras = {version="0.26.2", features = ["all_loaders"]}
egui_plot = "0.26.2"
gif = "0.13.1"
image = {version = "0.25.0", features = ["png"]}
itertools = "0.12.0"
nalgebra = {version = "0.32.3", features = ["serde-serialize"]}
ndarray = {version = "0.15.6", features = ["approx", "serde"]}
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.1"
num-traits = "0.2.15"
num-derive = "0.4.2"
nifti = "0.16.0"
physical_constants = "0.5.0"
plotters = "0.3.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
rubato = "0.15.0"
serde = "1.0.163"
scarlet = "1.2.0"
strum = "0.26.2"
strum_macros = "0.26.2"
toml = "0.8.2"
tracing = {version = "0.1.40", features = ["max_level_trace", "release_max_level_info"]}
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
test-log = "0.2.15"
wasm-bindgen = "0.2.89"
js-sys = "0.3"
serde_json = "1.0.108"
[dependencies.web-sys]
version = "0.3.22"
features = [
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "WebSocket",
]

[dev-dependencies]
criterion = "0.5.1"
ntest = "0.9.2"

[[bench]]
name = "run_epoch_benches"
harness = false

[[bench]]
name = "in_epoch_benches"
harness = false

[[bench]]
name = "in_system_prediction_benches"
harness = false

[[bench]]
name = "in_kalman_benches"
harness = false

[[bench]]
name = "in_update_benches"
harness = false

[[bench]]
name = "in_derivation_benches"
harness = false

[[bench]]
name = "in_metrics_benches"
harness = false

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "thin"
#codegen-units = 1