[package]
name = "rusty-cde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
bevy = "0.11.2"
bevy_egui = "0.22.0"
bevy_panorbit_camera = "0.8.0"
bevy-aabb-instancing = "0.10.0"
chrono = "0.4.24"
config = "0.13.3"
ciborium = "0.2.1"        
egui = "0.23.0"
egui_extras = {version="0.23.0", features = ["all_loaders"]}
fnv = "1.0.7"
gif = "0.12.0"
image = {version = "0.24.7", features = ["png"]}
itertools = "0.12.0"
lab = "0.11.0"
nalgebra = "0.32.3"
ndarray = {version = "0.15.6", features = ["approx", "serde", "rayon"]}
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.1"
num-traits = "0.2.15"
physical_constants = "0.5.0"
plotly = { version = "0.8.3", features = ["kaleido", "plotly_ndarray"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
rayon = "1.7.0"
samplerate = "0.2.4"
serde = "1.0.163"
strum = "0.25.0"
strum_macros = "0.25"
toml = "0.8.2"
color_quant = "1.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
ndarray-linalg = {version="0.16.0", features = ["intel-mkl-static"]}
[target.'cfg(target_os = "macos")'.dependencies]
ndarray-linalg = {version="0.16.0", features = ["openblas-system"]}

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.test]
opt-level = 3

[profile.release]
debug = true