[package]
name = "rusty-cde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
bevy = "0.12.1"
bevy_egui = "0.24.0"
bevy_panorbit_camera = "0.9.2"
chrono = "0.4.24"
config = "0.13.3"
ciborium = "0.2.1"        
egui = "0.24.1"
egui_extras = {version="0.24.2", features = ["all_loaders"]}
egui_plot = "0.24.0"
fnv = "1.0.7"
gif = "0.12.0"
image = {version = "0.24.7", features = ["png"]}
itertools = "0.12.0"
lab = "0.11.0"
nalgebra = {version = "0.32.3", features = ["serde-serialize"]}
ndarray = {version = "0.15.6", features = ["approx", "serde", "rayon"]}
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.1"
num-traits = "0.2.15"
physical_constants = "0.5.0"
plotters = "0.3.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
rayon = "1.7.0"
serde = "1.0.163"
scarlet = "1.2.0"
strum = "0.25.0"
strum_macros = "0.25"
toml = "0.8.2"
color_quant = "1.1.0"
wasm-bindgen = "0.2.89"
js-sys = "0.3"
serde_json = "1.0.108"
[dependencies.web-sys]
version = "0.3.22"
features = [
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "WebSocket",
]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.test]
opt-level = 3


[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1